### ISSUE TITLE
Cant read addresses 11,12

### ISSUE THREAD

**Issue by robertojguerra** [BrendanSweeny/pywatlow#3] opened 2022-04-08 03:59 UTC
Hello :) first comment in this project... I am very glad you have written this project :)

I am using the pywatlow in a RaspberryPi, with a daisychain of 12 Watlow temp controllers.

I am able to read the data from addresses 1 to 10, but I get an error with addresses 11 and 12
{'address': 11, 'param': None, 'data': None, 'error': Exception('Exception: No response from address 11')}

I tried the watlow daisychain with Watlow's own Easyconfigurator, and it is able to communicate with all Watlow devices.

Is there another way to access those addresses?

My python lines are:

watlow = Watlow(port='/dev/ttyUSB0', address=11)
print(watlow.readParam(4001, float))  # analog input

Thank you in advance for any suggestion!

If I need to provide a debug, or a serial bus log... I don't know how to do it, but you can point me to directions.

**Comment by BrendanSweeny** [comment] 2022-04-08 23:11
Hi Roberto,

Thanks for submitting the issue. I am glad you are finding this project useful!

After looking more closely at Easy Configurator, I am pretty sure it's a problem with hexadecimal conversion in pywatlow. I believe the problem is coming from how pywatlow is generating the address portion of the serial message. For addresses 1 - 10 it is correctly generating the corresponding blocks '10' through '19', but for address 11 it is generating '20' instead of '1A'.

I want to try it on some hardware to be sure, then write some tests and make sure it doesn't break anything. If I'm correct about the problem, I'll probably have a new build some time next week.

**Comment by robertojguerra** [comment] 2022-04-10 03:07
Thank you Brendan :)
I am finding this project very useful :D

**Comment by BrendanSweeny** [comment] 2022-04-16 00:00
Glad to hear it. The issue with the addresses should be fixed in version 0.1.4, which is on PyPI now.

**Closed by BrendanSweeny** 2022-04-16 00:00 UTC

**Comment by robertojguerra** [comment] 2022-04-18 06:14
Thank you for fixing this :D it works for me… I was able to readparams from address 11, 12
